<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Endpoint;

class ReplaceCoreV1NamespacedSecret extends \Flownative\Kubernetes\Api\Runtime\Client\BaseEndpoint implements \Flownative\Kubernetes\Api\Runtime\Client\Endpoint
{
    use \Flownative\Kubernetes\Api\Runtime\Client\EndpointTrait;
    protected $name;
    protected $namespace;

    /**
     * replace the specified Secret.
     *
     * @param string $name            name of the Secret
     * @param string $namespace       object name and auth scope, such as for teams and projects
     * @param array  $queryParameters {
     *
     * @var string $pretty If 'true', then the output is pretty printed. Defaults to 'false' unless the user-agent indicates a browser or command-line HTTP tool (curl and wget).
     * @var string $dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
     * @var string $fieldManager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
     * @var string $fieldValidation fieldValidation instructs the server on how to handle objects in the request (POST/PUT/PATCH) containing unknown or duplicate fields. Valid values are: - Ignore: This will ignore any unknown fields that are silently dropped from the object, and will ignore all but the last duplicate field that the decoder encounters. This is the default behavior prior to v1.23. - Warn: This will send a warning via the standard warning response header for each unknown field that is dropped from the object, and for each duplicate field that is encountered. The request will still succeed if there are no other errors, and will only persist the last of any duplicate fields. This is the default in v1.23+ - Strict: This will fail the request with a BadRequest error if any unknown fields would be dropped from the object, or if any duplicate fields are present. The error returned from the server will contain all unknown and duplicate fields encountered.
     *             }
     */
    public function __construct(string $name, string $namespace, \Flownative\Kubernetes\Api\Model\IoK8sApiCoreV1Secret $body, array $queryParameters = [])
    {
        $this->name = $name;
        $this->namespace = $namespace;
        $this->body = $body;
        $this->queryParameters = $queryParameters;
    }

    public function getMethod(): string
    {
        return 'PUT';
    }

    public function getUri(): string
    {
        return str_replace(['{name}', '{namespace}'], [$this->name, $this->namespace], '/api/v1/namespaces/{namespace}/secrets/{name}');
    }

    public function getBody(\Symfony\Component\Serializer\SerializerInterface $serializer, $streamFactory = null): array
    {
        return $this->getSerializedBody($serializer);
    }

    public function getExtraHeaders(): array
    {
        return ['Accept' => ['application/json']];
    }

    protected function getQueryOptionsResolver(): \Symfony\Component\OptionsResolver\OptionsResolver
    {
        $optionsResolver = parent::getQueryOptionsResolver();
        $optionsResolver->setDefined(['pretty', 'dryRun', 'fieldManager', 'fieldValidation']);
        $optionsResolver->setRequired([]);
        $optionsResolver->setDefaults([]);
        $optionsResolver->addAllowedTypes('pretty', ['string']);
        $optionsResolver->addAllowedTypes('dryRun', ['string']);
        $optionsResolver->addAllowedTypes('fieldManager', ['string']);
        $optionsResolver->addAllowedTypes('fieldValidation', ['string']);

        return $optionsResolver;
    }

    /**
     * @return \Flownative\Kubernetes\Api\Model\IoK8sApiCoreV1Secret
     *
     * @throws \Flownative\Kubernetes\Api\Exception\ReplaceCoreV1NamespacedSecretUnauthorizedException
     * @throws \Flownative\Kubernetes\Api\Exception\UnexpectedStatusCodeException
     */
    protected function transformResponseBody(\Psr\Http\Message\ResponseInterface $response, \Symfony\Component\Serializer\SerializerInterface $serializer, ?string $contentType = null)
    {
        $status = $response->getStatusCode();
        $body = (string) $response->getBody();
        if (200 === $status) {
            return $serializer->deserialize($body, 'Flownative\Kubernetes\Api\Model\IoK8sApiCoreV1Secret', 'json');
        }
        if (201 === $status) {
            return $serializer->deserialize($body, 'Flownative\Kubernetes\Api\Model\IoK8sApiCoreV1Secret', 'json');
        }
        if (401 === $status) {
            throw new \Flownative\Kubernetes\Api\Exception\ReplaceCoreV1NamespacedSecretUnauthorizedException($response);
        }
        throw new \Flownative\Kubernetes\Api\Exception\UnexpectedStatusCodeException($status, $body);
    }

    public function getAuthenticationScopes(): array
    {
        return ['BearerToken'];
    }
}
