<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Normalizer;

use Flownative\Kubernetes\Api\Runtime\Normalizer\CheckArray;
use Flownative\Kubernetes\Api\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class IoK8sApiCoreV1PodAffinityNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Flownative\Kubernetes\Api\Model\IoK8sApiCoreV1PodAffinity::class;
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \Flownative\Kubernetes\Api\Model\IoK8sApiCoreV1PodAffinity::class;
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \Flownative\Kubernetes\Api\Model\IoK8sApiCoreV1PodAffinity();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('preferredDuringSchedulingIgnoredDuringExecution', $data) && $data['preferredDuringSchedulingIgnoredDuringExecution'] !== null) {
            $values = [];
            foreach ($data['preferredDuringSchedulingIgnoredDuringExecution'] as $value) {
                $values[] = $this->denormalizer->denormalize($value, \Flownative\Kubernetes\Api\Model\IoK8sApiCoreV1WeightedPodAffinityTerm::class, 'json', $context);
            }
            $object->setPreferredDuringSchedulingIgnoredDuringExecution($values);
        } elseif (\array_key_exists('preferredDuringSchedulingIgnoredDuringExecution', $data) && $data['preferredDuringSchedulingIgnoredDuringExecution'] === null) {
            $object->setPreferredDuringSchedulingIgnoredDuringExecution(null);
        }
        if (\array_key_exists('requiredDuringSchedulingIgnoredDuringExecution', $data) && $data['requiredDuringSchedulingIgnoredDuringExecution'] !== null) {
            $values_1 = [];
            foreach ($data['requiredDuringSchedulingIgnoredDuringExecution'] as $value_1) {
                $values_1[] = $this->denormalizer->denormalize($value_1, \Flownative\Kubernetes\Api\Model\IoK8sApiCoreV1PodAffinityTerm::class, 'json', $context);
            }
            $object->setRequiredDuringSchedulingIgnoredDuringExecution($values_1);
        } elseif (\array_key_exists('requiredDuringSchedulingIgnoredDuringExecution', $data) && $data['requiredDuringSchedulingIgnoredDuringExecution'] === null) {
            $object->setRequiredDuringSchedulingIgnoredDuringExecution(null);
        }

        return $object;
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if ($data->isInitialized('preferredDuringSchedulingIgnoredDuringExecution') && null !== $data->getPreferredDuringSchedulingIgnoredDuringExecution()) {
            $values = [];
            foreach ($data->getPreferredDuringSchedulingIgnoredDuringExecution() as $value) {
                $values[] = $this->normalizer->normalize($value, 'json', $context);
            }
            $dataArray['preferredDuringSchedulingIgnoredDuringExecution'] = $values;
        }
        if ($data->isInitialized('requiredDuringSchedulingIgnoredDuringExecution') && null !== $data->getRequiredDuringSchedulingIgnoredDuringExecution()) {
            $values_1 = [];
            foreach ($data->getRequiredDuringSchedulingIgnoredDuringExecution() as $value_1) {
                $values_1[] = $this->normalizer->normalize($value_1, 'json', $context);
            }
            $dataArray['requiredDuringSchedulingIgnoredDuringExecution'] = $values_1;
        }

        return $dataArray;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [\Flownative\Kubernetes\Api\Model\IoK8sApiCoreV1PodAffinity::class => false];
    }
}
