<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Normalizer;

use Flownative\Kubernetes\Api\Runtime\Normalizer\CheckArray;
use Flownative\Kubernetes\Api\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class IoK8sApiCoreV1ISCSIVolumeSourceNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Flownative\Kubernetes\Api\Model\IoK8sApiCoreV1ISCSIVolumeSource::class;
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \Flownative\Kubernetes\Api\Model\IoK8sApiCoreV1ISCSIVolumeSource::class;
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \Flownative\Kubernetes\Api\Model\IoK8sApiCoreV1ISCSIVolumeSource();
        if (\array_key_exists('chapAuthDiscovery', $data) && \is_int($data['chapAuthDiscovery'])) {
            $data['chapAuthDiscovery'] = (bool) $data['chapAuthDiscovery'];
        }
        if (\array_key_exists('chapAuthSession', $data) && \is_int($data['chapAuthSession'])) {
            $data['chapAuthSession'] = (bool) $data['chapAuthSession'];
        }
        if (\array_key_exists('readOnly', $data) && \is_int($data['readOnly'])) {
            $data['readOnly'] = (bool) $data['readOnly'];
        }
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('chapAuthDiscovery', $data) && $data['chapAuthDiscovery'] !== null) {
            $object->setChapAuthDiscovery($data['chapAuthDiscovery']);
        } elseif (\array_key_exists('chapAuthDiscovery', $data) && $data['chapAuthDiscovery'] === null) {
            $object->setChapAuthDiscovery(null);
        }
        if (\array_key_exists('chapAuthSession', $data) && $data['chapAuthSession'] !== null) {
            $object->setChapAuthSession($data['chapAuthSession']);
        } elseif (\array_key_exists('chapAuthSession', $data) && $data['chapAuthSession'] === null) {
            $object->setChapAuthSession(null);
        }
        if (\array_key_exists('fsType', $data) && $data['fsType'] !== null) {
            $object->setFsType($data['fsType']);
        } elseif (\array_key_exists('fsType', $data) && $data['fsType'] === null) {
            $object->setFsType(null);
        }
        if (\array_key_exists('initiatorName', $data) && $data['initiatorName'] !== null) {
            $object->setInitiatorName($data['initiatorName']);
        } elseif (\array_key_exists('initiatorName', $data) && $data['initiatorName'] === null) {
            $object->setInitiatorName(null);
        }
        if (\array_key_exists('iqn', $data) && $data['iqn'] !== null) {
            $object->setIqn($data['iqn']);
        } elseif (\array_key_exists('iqn', $data) && $data['iqn'] === null) {
            $object->setIqn(null);
        }
        if (\array_key_exists('iscsiInterface', $data) && $data['iscsiInterface'] !== null) {
            $object->setIscsiInterface($data['iscsiInterface']);
        } elseif (\array_key_exists('iscsiInterface', $data) && $data['iscsiInterface'] === null) {
            $object->setIscsiInterface(null);
        }
        if (\array_key_exists('lun', $data) && $data['lun'] !== null) {
            $object->setLun($data['lun']);
        } elseif (\array_key_exists('lun', $data) && $data['lun'] === null) {
            $object->setLun(null);
        }
        if (\array_key_exists('portals', $data) && $data['portals'] !== null) {
            $values = [];
            foreach ($data['portals'] as $value) {
                $values[] = $value;
            }
            $object->setPortals($values);
        } elseif (\array_key_exists('portals', $data) && $data['portals'] === null) {
            $object->setPortals(null);
        }
        if (\array_key_exists('readOnly', $data) && $data['readOnly'] !== null) {
            $object->setReadOnly($data['readOnly']);
        } elseif (\array_key_exists('readOnly', $data) && $data['readOnly'] === null) {
            $object->setReadOnly(null);
        }
        if (\array_key_exists('secretRef', $data) && $data['secretRef'] !== null) {
            $object->setSecretRef($this->denormalizer->denormalize($data['secretRef'], \Flownative\Kubernetes\Api\Model\IoK8sApiCoreV1LocalObjectReference::class, 'json', $context));
        } elseif (\array_key_exists('secretRef', $data) && $data['secretRef'] === null) {
            $object->setSecretRef(null);
        }
        if (\array_key_exists('targetPortal', $data) && $data['targetPortal'] !== null) {
            $object->setTargetPortal($data['targetPortal']);
        } elseif (\array_key_exists('targetPortal', $data) && $data['targetPortal'] === null) {
            $object->setTargetPortal(null);
        }

        return $object;
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if ($data->isInitialized('chapAuthDiscovery') && null !== $data->getChapAuthDiscovery()) {
            $dataArray['chapAuthDiscovery'] = $data->getChapAuthDiscovery();
        }
        if ($data->isInitialized('chapAuthSession') && null !== $data->getChapAuthSession()) {
            $dataArray['chapAuthSession'] = $data->getChapAuthSession();
        }
        if ($data->isInitialized('fsType') && null !== $data->getFsType()) {
            $dataArray['fsType'] = $data->getFsType();
        }
        if ($data->isInitialized('initiatorName') && null !== $data->getInitiatorName()) {
            $dataArray['initiatorName'] = $data->getInitiatorName();
        }
        $dataArray['iqn'] = $data->getIqn();
        if ($data->isInitialized('iscsiInterface') && null !== $data->getIscsiInterface()) {
            $dataArray['iscsiInterface'] = $data->getIscsiInterface();
        }
        $dataArray['lun'] = $data->getLun();
        if ($data->isInitialized('portals') && null !== $data->getPortals()) {
            $values = [];
            foreach ($data->getPortals() as $value) {
                $values[] = $value;
            }
            $dataArray['portals'] = $values;
        }
        if ($data->isInitialized('readOnly') && null !== $data->getReadOnly()) {
            $dataArray['readOnly'] = $data->getReadOnly();
        }
        if ($data->isInitialized('secretRef') && null !== $data->getSecretRef()) {
            $dataArray['secretRef'] = $this->normalizer->normalize($data->getSecretRef(), 'json', $context);
        }
        $dataArray['targetPortal'] = $data->getTargetPortal();

        return $dataArray;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [\Flownative\Kubernetes\Api\Model\IoK8sApiCoreV1ISCSIVolumeSource::class => false];
    }
}
