<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiCoreV1ContainerStateWaiting
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Message regarding why the container is not yet running.
     *
     * @var string|null
     */
    protected $message;
    /**
     * (brief) reason the container is not yet running.
     *
     * @var string|null
     */
    protected $reason;

    /**
     * Message regarding why the container is not yet running.
     */
    public function getMessage(): ?string
    {
        return $this->message;
    }

    /**
     * Message regarding why the container is not yet running.
     */
    public function setMessage(?string $message): self
    {
        $this->initialized['message'] = true;
        $this->message = $message;

        return $this;
    }

    /**
     * (brief) reason the container is not yet running.
     */
    public function getReason(): ?string
    {
        return $this->reason;
    }

    /**
     * (brief) reason the container is not yet running.
     */
    public function setReason(?string $reason): self
    {
        $this->initialized['reason'] = true;
        $this->reason = $reason;

        return $this;
    }
}
