<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApimachineryPkgApisMetaV1StatusDetails
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The Causes array includes more details associated with the StatusReason failure. Not all StatusReasons may provide detailed causes.
     *
     * @var list<IoK8sApimachineryPkgApisMetaV1StatusCause>|null
     */
    protected $causes;
    /**
     * The group attribute of the resource associated with the status StatusReason.
     *
     * @var string|null
     */
    protected $group;
    /**
     * The kind attribute of the resource associated with the status StatusReason. On some operations may differ from the requested resource Kind. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds.
     *
     * @var string|null
     */
    protected $kind;
    /**
     * The name attribute of the resource associated with the status StatusReason (when there is a single name which can be described).
     *
     * @var string|null
     */
    protected $name;
    /**
     * If specified, the time in seconds before the operation should be retried. Some errors may indicate the client must take an alternate action - for those errors this field may indicate how long to wait before taking the alternate action.
     *
     * @var int|null
     */
    protected $retryAfterSeconds;
    /**
     * UID of the resource. (when there is a single resource which can be described). More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids.
     *
     * @var string|null
     */
    protected $uid;

    /**
     * The Causes array includes more details associated with the StatusReason failure. Not all StatusReasons may provide detailed causes.
     *
     * @return list<IoK8sApimachineryPkgApisMetaV1StatusCause>|null
     */
    public function getCauses(): ?array
    {
        return $this->causes;
    }

    /**
     * The Causes array includes more details associated with the StatusReason failure. Not all StatusReasons may provide detailed causes.
     *
     * @param list<IoK8sApimachineryPkgApisMetaV1StatusCause>|null $causes
     */
    public function setCauses(?array $causes): self
    {
        $this->initialized['causes'] = true;
        $this->causes = $causes;

        return $this;
    }

    /**
     * The group attribute of the resource associated with the status StatusReason.
     */
    public function getGroup(): ?string
    {
        return $this->group;
    }

    /**
     * The group attribute of the resource associated with the status StatusReason.
     */
    public function setGroup(?string $group): self
    {
        $this->initialized['group'] = true;
        $this->group = $group;

        return $this;
    }

    /**
     * The kind attribute of the resource associated with the status StatusReason. On some operations may differ from the requested resource Kind. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds.
     */
    public function getKind(): ?string
    {
        return $this->kind;
    }

    /**
     * The kind attribute of the resource associated with the status StatusReason. On some operations may differ from the requested resource Kind. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds.
     */
    public function setKind(?string $kind): self
    {
        $this->initialized['kind'] = true;
        $this->kind = $kind;

        return $this;
    }

    /**
     * The name attribute of the resource associated with the status StatusReason (when there is a single name which can be described).
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * The name attribute of the resource associated with the status StatusReason (when there is a single name which can be described).
     */
    public function setName(?string $name): self
    {
        $this->initialized['name'] = true;
        $this->name = $name;

        return $this;
    }

    /**
     * If specified, the time in seconds before the operation should be retried. Some errors may indicate the client must take an alternate action - for those errors this field may indicate how long to wait before taking the alternate action.
     */
    public function getRetryAfterSeconds(): ?int
    {
        return $this->retryAfterSeconds;
    }

    /**
     * If specified, the time in seconds before the operation should be retried. Some errors may indicate the client must take an alternate action - for those errors this field may indicate how long to wait before taking the alternate action.
     */
    public function setRetryAfterSeconds(?int $retryAfterSeconds): self
    {
        $this->initialized['retryAfterSeconds'] = true;
        $this->retryAfterSeconds = $retryAfterSeconds;

        return $this;
    }

    /**
     * UID of the resource. (when there is a single resource which can be described). More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids.
     */
    public function getUid(): ?string
    {
        return $this->uid;
    }

    /**
     * UID of the resource. (when there is a single resource which can be described). More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids.
     */
    public function setUid(?string $uid): self
    {
        $this->initialized['uid'] = true;
        $this->uid = $uid;

        return $this;
    }
}
