<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiCoreV1Capabilities
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Added capabilities.
     *
     * @var list<string>|null
     */
    protected $add;
    /**
     * Removed capabilities.
     *
     * @var list<string>|null
     */
    protected $drop;

    /**
     * Added capabilities.
     *
     * @return list<string>|null
     */
    public function getAdd(): ?array
    {
        return $this->add;
    }

    /**
     * Added capabilities.
     *
     * @param list<string>|null $add
     */
    public function setAdd(?array $add): self
    {
        $this->initialized['add'] = true;
        $this->add = $add;

        return $this;
    }

    /**
     * Removed capabilities.
     *
     * @return list<string>|null
     */
    public function getDrop(): ?array
    {
        return $this->drop;
    }

    /**
     * Removed capabilities.
     *
     * @param list<string>|null $drop
     */
    public function setDrop(?array $drop): self
    {
        $this->initialized['drop'] = true;
        $this->drop = $drop;

        return $this;
    }
}
