<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiCoreV1AttachedVolume
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * DevicePath represents the device path where the volume should be available.
     *
     * @var string|null
     */
    protected $devicePath;
    /**
     * Name of the attached volume.
     *
     * @var string|null
     */
    protected $name;

    /**
     * DevicePath represents the device path where the volume should be available.
     */
    public function getDevicePath(): ?string
    {
        return $this->devicePath;
    }

    /**
     * DevicePath represents the device path where the volume should be available.
     */
    public function setDevicePath(?string $devicePath): self
    {
        $this->initialized['devicePath'] = true;
        $this->devicePath = $devicePath;

        return $this;
    }

    /**
     * Name of the attached volume.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Name of the attached volume.
     */
    public function setName(?string $name): self
    {
        $this->initialized['name'] = true;
        $this->name = $name;

        return $this;
    }
}
