<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiCoreV1HostAlias
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Hostnames for the above IP address.
     *
     * @var list<string>|null
     */
    protected $hostnames;
    /**
     * IP address of the host file entry.
     *
     * @var string|null
     */
    protected $ip;

    /**
     * Hostnames for the above IP address.
     *
     * @return list<string>|null
     */
    public function getHostnames(): ?array
    {
        return $this->hostnames;
    }

    /**
     * Hostnames for the above IP address.
     *
     * @param list<string>|null $hostnames
     */
    public function setHostnames(?array $hostnames): self
    {
        $this->initialized['hostnames'] = true;
        $this->hostnames = $hostnames;

        return $this;
    }

    /**
     * IP address of the host file entry.
     */
    public function getIp(): ?string
    {
        return $this->ip;
    }

    /**
     * IP address of the host file entry.
     */
    public function setIp(?string $ip): self
    {
        $this->initialized['ip'] = true;
        $this->ip = $ip;

        return $this;
    }
}
