<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiCoreV1NodeDaemonEndpoints
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * DaemonEndpoint contains information about a single Daemon endpoint.
     *
     * @var IoK8sApiCoreV1DaemonEndpoint|null
     */
    protected $kubeletEndpoint;

    /**
     * DaemonEndpoint contains information about a single Daemon endpoint.
     */
    public function getKubeletEndpoint(): ?IoK8sApiCoreV1DaemonEndpoint
    {
        return $this->kubeletEndpoint;
    }

    /**
     * DaemonEndpoint contains information about a single Daemon endpoint.
     */
    public function setKubeletEndpoint(?IoK8sApiCoreV1DaemonEndpoint $kubeletEndpoint): self
    {
        $this->initialized['kubeletEndpoint'] = true;
        $this->kubeletEndpoint = $kubeletEndpoint;

        return $this;
    }
}
