<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiCoreV1NamespaceSpec
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Finalizers is an opaque list of values that must be empty to permanently remove object from storage. More info: https://kubernetes.io/docs/tasks/administer-cluster/namespaces/.
     *
     * @var list<string>|null
     */
    protected $finalizers;

    /**
     * Finalizers is an opaque list of values that must be empty to permanently remove object from storage. More info: https://kubernetes.io/docs/tasks/administer-cluster/namespaces/.
     *
     * @return list<string>|null
     */
    public function getFinalizers(): ?array
    {
        return $this->finalizers;
    }

    /**
     * Finalizers is an opaque list of values that must be empty to permanently remove object from storage. More info: https://kubernetes.io/docs/tasks/administer-cluster/namespaces/.
     *
     * @param list<string>|null $finalizers
     */
    public function setFinalizers(?array $finalizers): self
    {
        $this->initialized['finalizers'] = true;
        $this->finalizers = $finalizers;

        return $this;
    }
}
