<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiCoreV1DaemonEndpoint
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Port number of the given endpoint.
     *
     * @var int|null
     */
    protected $port;

    /**
     * Port number of the given endpoint.
     */
    public function getPort(): ?int
    {
        return $this->port;
    }

    /**
     * Port number of the given endpoint.
     */
    public function setPort(?int $port): self
    {
        $this->initialized['port'] = true;
        $this->port = $port;

        return $this;
    }
}
