<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiAppsV1DeploymentStrategy
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Spec to control the desired behavior of rolling update.
     *
     * @var IoK8sApiAppsV1RollingUpdateDeployment|null
     */
    protected $rollingUpdate;
    /**
     * Type of deployment. Can be "Recreate" or "RollingUpdate". Default is RollingUpdate.
     *
     * @var string|null
     */
    protected $type;

    /**
     * Spec to control the desired behavior of rolling update.
     */
    public function getRollingUpdate(): ?IoK8sApiAppsV1RollingUpdateDeployment
    {
        return $this->rollingUpdate;
    }

    /**
     * Spec to control the desired behavior of rolling update.
     */
    public function setRollingUpdate(?IoK8sApiAppsV1RollingUpdateDeployment $rollingUpdate): self
    {
        $this->initialized['rollingUpdate'] = true;
        $this->rollingUpdate = $rollingUpdate;

        return $this;
    }

    /**
     * Type of deployment. Can be "Recreate" or "RollingUpdate". Default is RollingUpdate.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Type of deployment. Can be "Recreate" or "RollingUpdate". Default is RollingUpdate.
     */
    public function setType(?string $type): self
    {
        $this->initialized['type'] = true;
        $this->type = $type;

        return $this;
    }
}
