<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiCoreV1ContainerUser
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * LinuxContainerUser represents user identity information in Linux containers.
     *
     * @var IoK8sApiCoreV1LinuxContainerUser|null
     */
    protected $linux;

    /**
     * LinuxContainerUser represents user identity information in Linux containers.
     */
    public function getLinux(): ?IoK8sApiCoreV1LinuxContainerUser
    {
        return $this->linux;
    }

    /**
     * LinuxContainerUser represents user identity information in Linux containers.
     */
    public function setLinux(?IoK8sApiCoreV1LinuxContainerUser $linux): self
    {
        $this->initialized['linux'] = true;
        $this->linux = $linux;

        return $this;
    }
}
