<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApimachineryPkgVersionInfo
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string|null
     */
    protected $buildDate;
    /**
     * @var string|null
     */
    protected $compiler;
    /**
     * EmulationMajor is the major version of the emulation version.
     *
     * @var string|null
     */
    protected $emulationMajor;
    /**
     * EmulationMinor is the minor version of the emulation version.
     *
     * @var string|null
     */
    protected $emulationMinor;
    /**
     * @var string|null
     */
    protected $gitCommit;
    /**
     * @var string|null
     */
    protected $gitTreeState;
    /**
     * @var string|null
     */
    protected $gitVersion;
    /**
     * @var string|null
     */
    protected $goVersion;
    /**
     * Major is the major version of the binary version.
     *
     * @var string|null
     */
    protected $major;
    /**
     * MinCompatibilityMajor is the major version of the minimum compatibility version.
     *
     * @var string|null
     */
    protected $minCompatibilityMajor;
    /**
     * MinCompatibilityMinor is the minor version of the minimum compatibility version.
     *
     * @var string|null
     */
    protected $minCompatibilityMinor;
    /**
     * Minor is the minor version of the binary version.
     *
     * @var string|null
     */
    protected $minor;
    /**
     * @var string|null
     */
    protected $platform;

    public function getBuildDate(): ?string
    {
        return $this->buildDate;
    }

    public function setBuildDate(?string $buildDate): self
    {
        $this->initialized['buildDate'] = true;
        $this->buildDate = $buildDate;

        return $this;
    }

    public function getCompiler(): ?string
    {
        return $this->compiler;
    }

    public function setCompiler(?string $compiler): self
    {
        $this->initialized['compiler'] = true;
        $this->compiler = $compiler;

        return $this;
    }

    /**
     * EmulationMajor is the major version of the emulation version.
     */
    public function getEmulationMajor(): ?string
    {
        return $this->emulationMajor;
    }

    /**
     * EmulationMajor is the major version of the emulation version.
     */
    public function setEmulationMajor(?string $emulationMajor): self
    {
        $this->initialized['emulationMajor'] = true;
        $this->emulationMajor = $emulationMajor;

        return $this;
    }

    /**
     * EmulationMinor is the minor version of the emulation version.
     */
    public function getEmulationMinor(): ?string
    {
        return $this->emulationMinor;
    }

    /**
     * EmulationMinor is the minor version of the emulation version.
     */
    public function setEmulationMinor(?string $emulationMinor): self
    {
        $this->initialized['emulationMinor'] = true;
        $this->emulationMinor = $emulationMinor;

        return $this;
    }

    public function getGitCommit(): ?string
    {
        return $this->gitCommit;
    }

    public function setGitCommit(?string $gitCommit): self
    {
        $this->initialized['gitCommit'] = true;
        $this->gitCommit = $gitCommit;

        return $this;
    }

    public function getGitTreeState(): ?string
    {
        return $this->gitTreeState;
    }

    public function setGitTreeState(?string $gitTreeState): self
    {
        $this->initialized['gitTreeState'] = true;
        $this->gitTreeState = $gitTreeState;

        return $this;
    }

    public function getGitVersion(): ?string
    {
        return $this->gitVersion;
    }

    public function setGitVersion(?string $gitVersion): self
    {
        $this->initialized['gitVersion'] = true;
        $this->gitVersion = $gitVersion;

        return $this;
    }

    public function getGoVersion(): ?string
    {
        return $this->goVersion;
    }

    public function setGoVersion(?string $goVersion): self
    {
        $this->initialized['goVersion'] = true;
        $this->goVersion = $goVersion;

        return $this;
    }

    /**
     * Major is the major version of the binary version.
     */
    public function getMajor(): ?string
    {
        return $this->major;
    }

    /**
     * Major is the major version of the binary version.
     */
    public function setMajor(?string $major): self
    {
        $this->initialized['major'] = true;
        $this->major = $major;

        return $this;
    }

    /**
     * MinCompatibilityMajor is the major version of the minimum compatibility version.
     */
    public function getMinCompatibilityMajor(): ?string
    {
        return $this->minCompatibilityMajor;
    }

    /**
     * MinCompatibilityMajor is the major version of the minimum compatibility version.
     */
    public function setMinCompatibilityMajor(?string $minCompatibilityMajor): self
    {
        $this->initialized['minCompatibilityMajor'] = true;
        $this->minCompatibilityMajor = $minCompatibilityMajor;

        return $this;
    }

    /**
     * MinCompatibilityMinor is the minor version of the minimum compatibility version.
     */
    public function getMinCompatibilityMinor(): ?string
    {
        return $this->minCompatibilityMinor;
    }

    /**
     * MinCompatibilityMinor is the minor version of the minimum compatibility version.
     */
    public function setMinCompatibilityMinor(?string $minCompatibilityMinor): self
    {
        $this->initialized['minCompatibilityMinor'] = true;
        $this->minCompatibilityMinor = $minCompatibilityMinor;

        return $this;
    }

    /**
     * Minor is the minor version of the binary version.
     */
    public function getMinor(): ?string
    {
        return $this->minor;
    }

    /**
     * Minor is the minor version of the binary version.
     */
    public function setMinor(?string $minor): self
    {
        $this->initialized['minor'] = true;
        $this->minor = $minor;

        return $this;
    }

    public function getPlatform(): ?string
    {
        return $this->platform;
    }

    public function setPlatform(?string $platform): self
    {
        $this->initialized['platform'] = true;
        $this->platform = $platform;

        return $this;
    }
}
