<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiCoreV1ServiceStatus
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Current service state.
     *
     * @var list<IoK8sApimachineryPkgApisMetaV1Condition>|null
     */
    protected $conditions;
    /**
     * LoadBalancerStatus represents the status of a load-balancer.
     *
     * @var IoK8sApiCoreV1LoadBalancerStatus|null
     */
    protected $loadBalancer;

    /**
     * Current service state.
     *
     * @return list<IoK8sApimachineryPkgApisMetaV1Condition>|null
     */
    public function getConditions(): ?array
    {
        return $this->conditions;
    }

    /**
     * Current service state.
     *
     * @param list<IoK8sApimachineryPkgApisMetaV1Condition>|null $conditions
     */
    public function setConditions(?array $conditions): self
    {
        $this->initialized['conditions'] = true;
        $this->conditions = $conditions;

        return $this;
    }

    /**
     * LoadBalancerStatus represents the status of a load-balancer.
     */
    public function getLoadBalancer(): ?IoK8sApiCoreV1LoadBalancerStatus
    {
        return $this->loadBalancer;
    }

    /**
     * LoadBalancerStatus represents the status of a load-balancer.
     */
    public function setLoadBalancer(?IoK8sApiCoreV1LoadBalancerStatus $loadBalancer): self
    {
        $this->initialized['loadBalancer'] = true;
        $this->loadBalancer = $loadBalancer;

        return $this;
    }
}
