<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiCoreV1DownwardAPIProjection
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Items is a list of DownwardAPIVolume file.
     *
     * @var list<IoK8sApiCoreV1DownwardAPIVolumeFile>|null
     */
    protected $items;

    /**
     * Items is a list of DownwardAPIVolume file.
     *
     * @return list<IoK8sApiCoreV1DownwardAPIVolumeFile>|null
     */
    public function getItems(): ?array
    {
        return $this->items;
    }

    /**
     * Items is a list of DownwardAPIVolume file.
     *
     * @param list<IoK8sApiCoreV1DownwardAPIVolumeFile>|null $items
     */
    public function setItems(?array $items): self
    {
        $this->initialized['items'] = true;
        $this->items = $items;

        return $this;
    }
}
