<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiCoreV1SecretKeySelector
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The key of the secret to select from.  Must be a valid secret key.
     *
     * @var string|null
     */
    protected $key;
    /**
     * Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names.
     *
     * @var string|null
     */
    protected $name;
    /**
     * Specify whether the Secret or its key must be defined.
     *
     * @var bool|null
     */
    protected $optional;

    /**
     * The key of the secret to select from.  Must be a valid secret key.
     */
    public function getKey(): ?string
    {
        return $this->key;
    }

    /**
     * The key of the secret to select from.  Must be a valid secret key.
     */
    public function setKey(?string $key): self
    {
        $this->initialized['key'] = true;
        $this->key = $key;

        return $this;
    }

    /**
     * Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names.
     */
    public function setName(?string $name): self
    {
        $this->initialized['name'] = true;
        $this->name = $name;

        return $this;
    }

    /**
     * Specify whether the Secret or its key must be defined.
     */
    public function getOptional(): ?bool
    {
        return $this->optional;
    }

    /**
     * Specify whether the Secret or its key must be defined.
     */
    public function setOptional(?bool $optional): self
    {
        $this->initialized['optional'] = true;
        $this->optional = $optional;

        return $this;
    }
}
