<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiCoreV1NodeAddress
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The node address.
     *
     * @var string|null
     */
    protected $address;
    /**
     * Node address type, one of Hostname, ExternalIP or InternalIP.
     *
     * @var string|null
     */
    protected $type;

    /**
     * The node address.
     */
    public function getAddress(): ?string
    {
        return $this->address;
    }

    /**
     * The node address.
     */
    public function setAddress(?string $address): self
    {
        $this->initialized['address'] = true;
        $this->address = $address;

        return $this;
    }

    /**
     * Node address type, one of Hostname, ExternalIP or InternalIP.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Node address type, one of Hostname, ExternalIP or InternalIP.
     */
    public function setType(?string $type): self
    {
        $this->initialized['type'] = true;
        $this->type = $type;

        return $this;
    }
}
