<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiCoreV1PhotonPersistentDiskVolumeSource
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * fsType is the filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. "ext4", "xfs", "ntfs". Implicitly inferred to be "ext4" if unspecified.
     *
     * @var string|null
     */
    protected $fsType;
    /**
     * pdID is the ID that identifies Photon Controller persistent disk.
     *
     * @var string|null
     */
    protected $pdID;

    /**
     * fsType is the filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. "ext4", "xfs", "ntfs". Implicitly inferred to be "ext4" if unspecified.
     */
    public function getFsType(): ?string
    {
        return $this->fsType;
    }

    /**
     * fsType is the filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. "ext4", "xfs", "ntfs". Implicitly inferred to be "ext4" if unspecified.
     */
    public function setFsType(?string $fsType): self
    {
        $this->initialized['fsType'] = true;
        $this->fsType = $fsType;

        return $this;
    }

    /**
     * pdID is the ID that identifies Photon Controller persistent disk.
     */
    public function getPdID(): ?string
    {
        return $this->pdID;
    }

    /**
     * pdID is the ID that identifies Photon Controller persistent disk.
     */
    public function setPdID(?string $pdID): self
    {
        $this->initialized['pdID'] = true;
        $this->pdID = $pdID;

        return $this;
    }
}
