<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApimachineryPkgApisMetaV1LabelSelector
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * matchExpressions is a list of label selector requirements. The requirements are ANDed.
     *
     * @var list<IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement>|null
     */
    protected $matchExpressions;
    /**
     * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
     *
     * @var array<string, string>|null
     */
    protected $matchLabels;

    /**
     * matchExpressions is a list of label selector requirements. The requirements are ANDed.
     *
     * @return list<IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement>|null
     */
    public function getMatchExpressions(): ?array
    {
        return $this->matchExpressions;
    }

    /**
     * matchExpressions is a list of label selector requirements. The requirements are ANDed.
     *
     * @param list<IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement>|null $matchExpressions
     */
    public function setMatchExpressions(?array $matchExpressions): self
    {
        $this->initialized['matchExpressions'] = true;
        $this->matchExpressions = $matchExpressions;

        return $this;
    }

    /**
     * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
     *
     * @return array<string, string>|null
     */
    public function getMatchLabels(): ?iterable
    {
        return $this->matchLabels;
    }

    /**
     * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
     *
     * @param array<string, string>|null $matchLabels
     */
    public function setMatchLabels(?iterable $matchLabels): self
    {
        $this->initialized['matchLabels'] = true;
        $this->matchLabels = $matchLabels;

        return $this;
    }
}
