<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiCoreV1Sysctl
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Name of a property to set.
     *
     * @var string|null
     */
    protected $name;
    /**
     * Value of a property to set.
     *
     * @var string|null
     */
    protected $value;

    /**
     * Name of a property to set.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Name of a property to set.
     */
    public function setName(?string $name): self
    {
        $this->initialized['name'] = true;
        $this->name = $name;

        return $this;
    }

    /**
     * Value of a property to set.
     */
    public function getValue(): ?string
    {
        return $this->value;
    }

    /**
     * Value of a property to set.
     */
    public function setValue(?string $value): self
    {
        $this->initialized['value'] = true;
        $this->value = $value;

        return $this;
    }
}
