<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiCoreV1NodeRuntimeHandlerFeatures
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * RecursiveReadOnlyMounts is set to true if the runtime handler supports RecursiveReadOnlyMounts.
     *
     * @var bool|null
     */
    protected $recursiveReadOnlyMounts;
    /**
     * UserNamespaces is set to true if the runtime handler supports UserNamespaces, including for volumes.
     *
     * @var bool|null
     */
    protected $userNamespaces;

    /**
     * RecursiveReadOnlyMounts is set to true if the runtime handler supports RecursiveReadOnlyMounts.
     */
    public function getRecursiveReadOnlyMounts(): ?bool
    {
        return $this->recursiveReadOnlyMounts;
    }

    /**
     * RecursiveReadOnlyMounts is set to true if the runtime handler supports RecursiveReadOnlyMounts.
     */
    public function setRecursiveReadOnlyMounts(?bool $recursiveReadOnlyMounts): self
    {
        $this->initialized['recursiveReadOnlyMounts'] = true;
        $this->recursiveReadOnlyMounts = $recursiveReadOnlyMounts;

        return $this;
    }

    /**
     * UserNamespaces is set to true if the runtime handler supports UserNamespaces, including for volumes.
     */
    public function getUserNamespaces(): ?bool
    {
        return $this->userNamespaces;
    }

    /**
     * UserNamespaces is set to true if the runtime handler supports UserNamespaces, including for volumes.
     */
    public function setUserNamespaces(?bool $userNamespaces): self
    {
        $this->initialized['userNamespaces'] = true;
        $this->userNamespaces = $userNamespaces;

        return $this;
    }
}
