<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiCoreV1EphemeralVolumeSource
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * PersistentVolumeClaimTemplate is used to produce PersistentVolumeClaim objects as part of an EphemeralVolumeSource.
     *
     * @var IoK8sApiCoreV1PersistentVolumeClaimTemplate|null
     */
    protected $volumeClaimTemplate;

    /**
     * PersistentVolumeClaimTemplate is used to produce PersistentVolumeClaim objects as part of an EphemeralVolumeSource.
     */
    public function getVolumeClaimTemplate(): ?IoK8sApiCoreV1PersistentVolumeClaimTemplate
    {
        return $this->volumeClaimTemplate;
    }

    /**
     * PersistentVolumeClaimTemplate is used to produce PersistentVolumeClaim objects as part of an EphemeralVolumeSource.
     */
    public function setVolumeClaimTemplate(?IoK8sApiCoreV1PersistentVolumeClaimTemplate $volumeClaimTemplate): self
    {
        $this->initialized['volumeClaimTemplate'] = true;
        $this->volumeClaimTemplate = $volumeClaimTemplate;

        return $this;
    }
}
