<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiCoreV1NodeSwapStatus
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Total amount of swap memory in bytes.
     *
     * @var int|null
     */
    protected $capacity;

    /**
     * Total amount of swap memory in bytes.
     */
    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    /**
     * Total amount of swap memory in bytes.
     */
    public function setCapacity(?int $capacity): self
    {
        $this->initialized['capacity'] = true;
        $this->capacity = $capacity;

        return $this;
    }
}
