<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiCoreV1ContainerResizePolicy
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Name of the resource to which this resource resize policy applies. Supported values: cpu, memory.
     *
     * @var string|null
     */
    protected $resourceName;
    /**
     * Restart policy to apply when specified resource is resized. If not specified, it defaults to NotRequired.
     *
     * @var string|null
     */
    protected $restartPolicy;

    /**
     * Name of the resource to which this resource resize policy applies. Supported values: cpu, memory.
     */
    public function getResourceName(): ?string
    {
        return $this->resourceName;
    }

    /**
     * Name of the resource to which this resource resize policy applies. Supported values: cpu, memory.
     */
    public function setResourceName(?string $resourceName): self
    {
        $this->initialized['resourceName'] = true;
        $this->resourceName = $resourceName;

        return $this;
    }

    /**
     * Restart policy to apply when specified resource is resized. If not specified, it defaults to NotRequired.
     */
    public function getRestartPolicy(): ?string
    {
        return $this->restartPolicy;
    }

    /**
     * Restart policy to apply when specified resource is resized. If not specified, it defaults to NotRequired.
     */
    public function setRestartPolicy(?string $restartPolicy): self
    {
        $this->initialized['restartPolicy'] = true;
        $this->restartPolicy = $restartPolicy;

        return $this;
    }
}
