<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Kubernetes\Api\Model;

class IoK8sApiCoreV1PodReadinessGate
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * ConditionType refers to a condition in the pod's condition list with matching type.
     *
     * @var string|null
     */
    protected $conditionType;

    /**
     * ConditionType refers to a condition in the pod's condition list with matching type.
     */
    public function getConditionType(): ?string
    {
        return $this->conditionType;
    }

    /**
     * ConditionType refers to a condition in the pod's condition list with matching type.
     */
    public function setConditionType(?string $conditionType): self
    {
        $this->initialized['conditionType'] = true;
        $this->conditionType = $conditionType;

        return $this;
    }
}
